services:
  - type: web
    name: inzaghi-food-ai-backend
    env: python
    plan: free
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false # You will need to enter this value in the Render dashboard
